
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Download, Calendar, BarChart3, DollarSign, Users, Plus } from "lucide-react";
import { useState } from "react";

import { reports } from "@/lib/mock-data";

const iconMap = {
  Financial: DollarSign,
  Resource: Users,
  Client: BarChart3,
};

const OwnerReports = () => {
  const [reportType, setReportType] = useState("financial");
  const [dateRange, setDateRange] = useState("q3-2024");

  return (
    <main className="flex-1 px-6 py-8">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center space-x-3">
          <FileText className="w-8 h-8 text-primary" />
          <div>
            <h1 className="text-2xl font-bold text-foreground">Executive Reports</h1>
            <p className="text-sm text-muted-foreground">Generate and download detailed company reports</p>
          </div>
        </div>
        <Button>
          <Plus className="w-4 h-4 mr-2" />
          Generate New Report
        </Button>
      </div>

      {/* Report Generation Section */}
      <Card className="mb-8">
        <CardHeader>
          <CardTitle>Generate a New Report</CardTitle>
          <CardDescription>Select the report type and date range to generate a new document.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex flex-col sm:flex-row gap-4">
            <div className="flex-1">
              <label htmlFor="report-type" className="text-sm font-medium mb-2 block">Report Type</label>
              <Select value={reportType} onValueChange={setReportType}>
                <SelectTrigger id="report-type">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="financial">Financial Performance</SelectItem>
                  <SelectItem value="project">Project Portfolio</SelectItem>
                  <SelectItem value="team">Team & Resource</SelectItem>
                  <SelectItem value="client">Client Engagement</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex-1">
              <label htmlFor="date-range" className="text-sm font-medium mb-2 block">Date Range</label>
              <Select value={dateRange} onValueChange={setDateRange}>
                <SelectTrigger id="date-range">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="last-30d">Last 30 Days</SelectItem>
                  <SelectItem value="q3-2024">Q3 2024</SelectItem>
                  <SelectItem value="q2-2024">Q2 2024</SelectItem>
                  <SelectItem value="h1-2024">First Half 2024</SelectItem>
                  <SelectItem value="2023">Full Year 2023</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex items-end">
              <Button size="lg" className="w-full sm:w-auto">
                <Download className="w-4 h-4 mr-2" />
                Generate & Download
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Recently Generated Reports */}
      <Card>
        <CardHeader>
          <CardTitle>Recently Generated Reports</CardTitle>
          <CardDescription>Access and download previously generated reports.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {reports.map((report) => {
              const Icon = iconMap[report.type as keyof typeof iconMap] || FileText;
              return (
                <div key={report.id} className="flex items-center justify-between p-4 border rounded-lg hover:bg-muted/50">
                  <div className="flex items-center space-x-4">
                    <div className="bg-secondary p-3 rounded-lg">
                      <Icon className="w-6 h-6 text-primary" />
                    </div>
                    <div>
                      <p className="font-semibold">{report.title}</p>
                      <p className="text-sm text-muted-foreground">Generated by {report.generatedBy}</p>
                    </div>
                  </div>
                  <div className="text-right">
                     <Button variant="outline">
                        <Download className="w-4 h-4 mr-2" />
                        Download
                      </Button>
                    <p className="text-xs text-muted-foreground mt-2">
                      Generated on {new Date(report.generatedDate).toLocaleDateString()} | {report.period}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
    </main>
  );
};

export default OwnerReports;
